---

plugins:
  - jest
  - babel

env:
  node: true
  jest/globals: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'eslint:recommended'
  - 'plugin:react/recommended'

rules:
  no-console: 0
  react/prop-types: 0

settings:
  react:
    version: 'detect'