# This is a basic workflow to help you get started with Actions

name: Run-tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
env:
  GO_VERSION: 0.0.1
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: set up go ${{env.GO_VERSION}}
      uses: actions/setup-go@v1
      with:
        go-version: ${{env.GO_VERSION}}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: ./build.sh
    - name: Test
      run: go test -count=1 -v ./...
