name: Run-tests
on:
  workflow_dispatch:
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
       node-version: '13.x'
   - name: Install Dependencies
     run: npm install

      
