  
name: Node CI

on:
  - workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: npm install
        run: npm install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
