name: Run-tests
on:
  workflow_dispatch:
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: install deps
      run: npm install https://github.com/Vadimusss/frontend-project-lvl4.git
    - name: Run tests
      run: make test
