name: Run-tests
on:
  workflow_dispatch:
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: install deps
      run: npm install
    - name: Run tests
      run: make test
